language: cpp

script: make test

compiler: gcc

install:
  - export CXX="g++-4.9"

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
